### PR TITLE
P1 / P4 File Support

### PR DESCRIPTION
**Pull request by BenWeisz**
I've added support for the .pbm file formats (P1/P4), as well as made some small changes to the number of bytes the parser reads so that we have a more stable parser. I've also added a few extra sample images.

Since we know support all the NetPBM formats we should probably:
1) Rename the extension to NetPBM viewer
OR
2) Change the repo name to pbm-ppm-pgm-viewer-for-vscode

Let me know what you think, thanks!

### CODE REVIEW

**Review by nagata-yoshiteru — APPROVED** [review]
Thank you for adding new feature, @BenWeisz !

Your P1/P4 support and new bytes parser seem to working well in my environment.

I think we should add "pbm" to the repo/extension name because some people use a filename extension ( like "pbm" or "pgm" ) to find out a VSCode extension which support the file format.
So, I approve your current change!
Also, how about incrementing "major" or "minor" version number because you made a big update and we will change extention name at this time.

I will update the repo name / `package.json` repo url after you check my review!

Thanks!

**Comment by BenWeisz** [comment]
@nagata-yoshiteru That sounds good to me, we can bump the verson! I've tried to add the pbm to a few places but there might be some that are missing.

Thanks for the review :)

**Comment by nagata-yoshiteru** [comment]
@BenWeisz Thanks for your quick reply!

I will update the repo name, `package.json` and double check to add "pbm" !
However, I think we should not change the extension's identifier ( `ppm-pgm-viewer-for-vscode` ) because we will fail to publish the extension once we change it, so I will leave it as it is.

**Comment by nagata-yoshiteru** [comment]
@BenWeisz I updated repo name, and double checked to add "pbm" ( and there is no missing point! )
Also, I bumped version up to `1.0.0`!

If there are no problem, I will merge this PR and publish new version!
Thanks!

**Comment by BenWeisz** [comment]
Awesome! Feel free to publish it :)

**Pull request merged**
