### PR TITLE
Add copy button

### PR DESCRIPTION
**Pull request by santaclose**
I added a copy button which i think is very convenient to have and I'm always missing.

### CODE REVIEW

**Comment by nagata-yoshiteru** [comment]
Hi, @santaclose !
Thank you for your PR!
I tested your code and worked fine in my environment!

One point, I thought it would be easier to understand if the 'Copy' button was labeled 'Copy to Clipboard'.
However, the width of `styles.info` needs to be adjusted (in my environment, 120px fits in one line) because the number of characters becomes too large and lines are broken.

Hello @BenWeisz , long time no see! How do you think about this?

**Comment by santaclose** [comment]
Thanks for replying! yeah I was initially using "Copy to clipboard" as the label and had the same issue so I cut it down to "Copy". I'm fine with whatever you guys decide for the style.

**Comment by BenWeisz** [comment]
Hi there 👋

Thanks for adding this! I agree with @nagata-yoshiteru, "Copy to Clipboard" would probably be better wording. If didn't mind, could you also please move the copy div above the save button's div?

I've just re-formatted by computer so I don't have node installed or the project cloned, so it might take me a couple days to test this.

**Comment by nagata-yoshiteru** [comment]
Thanks @santaclose and @BenWeisz !

I also agree with moving the copy button above the save button.
So @santaclose, if you don't mind, please implement what we have discussed so far.

Thanks!

**Comment by santaclose** [comment]
updated the commit

**Comment by nagata-yoshiteru** [comment]
Hi, @BenWeisz !

Have you tested this PR?
If you are busy now, I will merge it as I don't see any problem in this PR.
Then, if you see something that needs to be improved, correct it in another PR.

Thanks!

**Comment by BenWeisz** [comment]
Hi @nagata-yoshiteru,

I unfortunately haven't had the time yet to set up the project again. Feel free to merge the PR, I should be able to check the code sometime next week.

Thanks!

**Review by nagata-yoshiteru — APPROVED** [review]

**Comment by nagata-yoshiteru** [comment]
Hi, @santaclose !

We usually add the contributor's name to `README.md`.
I would like to add your name and nationality in `README.md` if you don't mind, so let me know your nationality if you prefer!

Thanks!

**Comment by santaclose** [comment]
Hi I'm Venezuelan

**Comment by nagata-yoshiteru** [comment]
Thanks @santaclose !

I have added your name and nationality in `README.md`, so please let me know if there is something wrong.
I also have published v1.2.0 that contains your commit.

Thanks!

**Comment by BenWeisz** [comment]
@nagata-yoshiteru I just got around to testing this, but it looks like its working : )

**Pull request merged**
