### PR TITLE
parsing.ts: properly handle P5/P6 images with Maxval >255

### LINKED ISSUE #35: P6 with maxval > 255 not rendered correctly
When a P6 has a maxval (denominator) greater than 255, each color is stored in **two bytes** but the extension code is only reading 1 byte, meaning that a completely wrong image is shown (because each pixel's 6 bytes are interpreted as 2 different pixels, the first from the RRG bytes and the second from the GBB bytes). See https://linux.die.net/man/5/ppm and https://github.com/nagata-yoshiteru/pbm-ppm-pgm-viewer-for-vscode/blob/2d5f0052845120f51eb5204234f2bcd1d8de4b24/src/parsing.ts#L209-L217

### PR DESCRIPTION
**Pull request by DanielS6**
When the Maxval is greater than 255, the colors for each pixel are stored in 2 bytes rather than just 1.

Includes addition of two new image files - p6-one-byte.ppm and p6-two-bytes.ppm The former comes from https://commons.wikimedia.org/wiki/File:Example.png, which is in the public domain, and the latter is the same image with a Maxval of 512 - they should appear the same when rendered.

Fixes #35

### CODE REVIEW

**Comment by BenWeisz** [comment]
So it looks like the two byte file is severely white shifted compared to the first image. Looking at a hex dump, the pixel data differs quite a bit. Did you generate the second file by doubling the pixel intensities?

In the 1 byte file the first data point is `0xf4` --> `244` which if doubled should be `488` --> `0x01E8` or `0xE801` depending on the endian. It looks like the first two bytes in the other file are `0x01ea` which doesn't seem right either way

**Comment by BenWeisz** [comment]
Other than that the code seems to be handling the different amounts of data correctly :)

**Comment by DanielS6** [comment]
> So it looks like the two byte file is severely white shifted compared to the first image. Looking at a hex dump, the pixel data differs quite a bit. Did you generate the second file by doubling the pixel intensities?
> 
> In the 1 byte file the first data point is `0xf4` --> `244` which if doubled should be `488` --> `0x01E8` or `0xE801` depending on the endian. It looks like the first two bytes in the other file are `0x01ea` which doesn't seem right either way

I just used https://linux.die.net/man/1/pamdepth to change the Maxval from 255 to 512, which is slightly more than double. The pixels are stored with the most significant byte first, and `0x01E8` (from doubling) is just under the actual `0x01EA` (from slightly more than doubling). If you have a different image that you would prefer thats fine

**Comment by BenWeisz** [comment]
@DanielS6 ok so I took a look at the code and the issue was that the proper scaling wasn't done when sending it to the display. As far as I know the display code we use can only work with 256 values for each channel so the way we've implemented it is that during file parsing the data gets converted to a range on the scale of 0-255 regardless of the magic number. This ruins the fidelity of the image for higher channel resolution images but I guess it is what it is for now 🤷‍♂️. At least the image is still viewable

**Review by BenWeisz — APPROVED** [review]

**Comment by DanielS6** [comment]
> @DanielS6 ok so I took a look at the code and the issue was that the proper scaling wasn't done when sending it to the display. As far as I know the display code we use can only work with 256 values for each channel so the way we've implemented it is that during file parsing the data gets converted to a range on the scale of 0-255 regardless of the magic number. This ruins the fidelity of the image for higher channel resolution images but I guess it is what it is for now 🤷‍♂️. At least the image is still viewable

That makes sense - thanks for identifying the problem and adding your fix - looks good to me

**Comment by DanielS6** [comment]
> @nagata-yoshiteru Feel to merge this PR, it works fine for me on MacOS don't see any other platform issues (NetBPM specifies that the most significant bits must come first in the file so it should be the same on all platforms)

Once merged can you please make a release as soon as you have time? I came across this issue because it was causing problems with a project I'm currently working on

> @DanielS6 What is your nationality? We can add you to the list of people who've worked on the project in the readme :)

I'm fine being listed in the README but (without going in to my speech about how code should speak for itself) I'd prefer not to have my nationality included

**Comment by BenWeisz** [comment]
I think the project owner is still waking up so it may take a bit of time because he's the only one that can publish the extension

**Review by nagata-yoshiteru — APPROVED** [review]
Hi, @DanielS6 @BenWeisz !
I'm sorry for my late response, but I've tested the code and worked fine for my Windows envitonment.
So I will merge this PR and publish new version!

@DanielS6 Can I add your name (without nationality) in `README.md` after merging this PR?

**Comment by DanielS6** [comment]
> Hi, @DanielS6 @BenWeisz ! I'm sorry for my late response, but I've tested the code and worked fine for my Windows envitonment. So I will merge this PR and publish new version!

Thanks so much!

> @DanielS6 Can I add your name (without nationality) in `README.md` after merging this PR?

Sure, just list me as @DanielS6

**Comment by DanielS6** [comment]
@nagata-yoshiteru I confirmed that 1.1.2 is available in VSCode, upgraded, and confirmed that I can now see the image - thanks so much for the prompt review (also @BenWeisz)

**Pull request merged**
